baseURL = "http://boxcounter.com/"
languageCode = "zh-cn"
title = "Boxcounter's blog"
theme = "yinyang"
googleAnalytics = "UA-1017426-4"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

[author]
  name = "Boxcounter"
  homepage = "http://boxcounter.com/"

[params]
  math = true
  #disqus = "boxcounter"

[markup]
  [markup.highlight]
    style = 'manni'
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
